version: '3'

services:
  concourse-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: lukedapuzzo
      POSTGRES_USER: devondapuzzo
      POSTGRES_PASSWORD: pswd1234
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["9999:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
#      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: devondapuzzo
      CONCOURSE_POSTGRES_PASSWORD: pswd1234
      CONCOURSE_POSTGRES_DATABASE: lukedapuzzo
      CONCOURSE_POSTGRES_URL: jdbc:postgresql://concourse-db:5432/lukedapuzzo&currentSchema=test

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web