---
resources:
- name: luke-dapuzzo-app
  type: git
  source:
    uri: https://github.com/djdapz/lukeDapuzzo.git

jobs:
- name: test-luke-app
  public: true
  plan:
  - get: luke-dapuzzo-app
    trigger: true
  - task: web-app-tests
    file: luke-dapuzzo-app/pipeline/run-tests.yml
