---
resources:
- name: luke-dapuzzo-app
  type: git
  source:
    uri: git@github.com:djdapz/lukeDapuzzo.git
    private_key: ((github-private-key))
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:djdapz/lukeDapuzzo.git
    branch: version
    file: version
    private_key: ((github-private-key))

jobs:
- name: unit-and-integration-tests
  public: true
  plan:
  - get: luke-dapuzzo-app
    trigger: true
  - get: version
    params: {bump: patch}
    trigger: false
  - task: unit-and-integration-tests
    file: luke-dapuzzo-app/pipeline/run-tests.yml

- name: deploy-client-development
  public: true
  plan:
  - get: luke-dapuzzo-app
    trigger: true
    passed: [unit-and-integration-tests]
  - get: version
    trigger: false
  - task: build-and-deploy
    file: luke-dapuzzo-app/pipeline/deploy-backend-client.yml

- name: deploy-backend-development
  public: true
  plan:
  - get: luke-dapuzzo-app
    trigger: true
    passed: [unit-and-integration-tests]
  - get: version
    trigger: false
  - task: build-and-deploy
    file: luke-dapuzzo-app/pipeline/deploy-client-dev.yml


