---
resources:
- name: luke-dapuzzo-app
  type: git
  source:
    uri: git@github.com:djdapz/lukeDapuzzo.git
    private_key: ((github-private-key))
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:djdapz/lukeDapuzzo.git
    branch: version
    file: version
    private_key: ((github-private-key))

jobs:
- name: test-luke-app
  public: true
  plan:
  - get: luke-dapuzzo-app
    trigger: true
  - get: version
    trigger: false
  - task: unit-and-integration-tests
    file: luke-dapuzzo-app/pipeline/run-tests.yml
