spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/luke-test
    password: lukepwd
    username: lukeuser

dapuzzo:
  luke:
    whitelist: /login, /account/create, /email
    email-distribution-list: djdapz@aol.com
    email-service: http://localhost:8082
    jwt:
      secret: IM_SUPER_SECRET_YO
      seconds-token-is-valid: 10000
      issuer: luke-test-local.io

server:
  port: 8081
