spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lukedapuzzo?currentSchema=local
    password:
    username: devondapuzzo

dapuzzo:
  luke:
    client:
      url: http://localhost:9000/bundle.js
    email-distribution-list: devon@dapuzzo.com,djdapz@aol.com

server:
  port: 8080
