spring:
  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    username: devondapuzzotesting@gmail.com
    password: dEvonwEBSITE
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  datasource:
    url: jdbc:postgresql://ec2-54-163-232-171.compute-1.amazonaws.com:5432/d4536c32hqd2f6?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    password: cd09f011c78b7c212307967c150eec20c7adf71b291afe62df23d2918bfdec08
    username: cwmiwmoyucqpmr
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create
        temp:
          use_jdbc_metadata_defaults: false
  profiles:
    active: local


