server:
  port: ${PORT}

dapuzzo:
  luke:
    whitelist: /login

spring:
  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${LUKE_EMAIL_ADDRESS}
    password: ${LUKE_EMAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  datasource:
    url: ${LUKE_DATABASE_URL}
    password: ${LUKE_DATABASE_PASSWORD}
    username: ${LUKE_DATABASE_USERNAME}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/fixtures,classpath:db/migration
    clean-on-validation-error: false