spring:
  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    username: devondapuzzotesting@gmail.com
    password: dEvonwEBSITE
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create
        temp:
          use_jdbc_metadata_defaults: false

flyway:
  locations: classpath:db/migration,classpath:db/fixtures
  clean-on-validation-error: true


