spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/luke-test
    password: lukepwd
    username: lukeuser

dapuzzo:
  luke:
    email-distribution-list: devon@dapuzzo.com,djdapz@aol.com

server:
  port: 8081
