spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lukedapuzzo
    password:
    username: devondapuzzo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: local

flyway:
  schemas: local
