spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lukedapuzzo?currentSchema=blah
    password:
    username: devondapuzzo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: blah

dapuzzo:
  luke:
    client:
      url: http://localhost:9000/bundle.js

flyway:
  schemas: blah
