---
platform: linux

inputs:
- name: repo
- name: version

params:
  pcf-username:
  pcf-password:
  pcf-space:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: repo/ci/tasks/deploy-cf.sh

caches:
  - path: gradle