---
platform: linux

#image_resource:
#  type: docker-image
#  source:
#    repository: openjdk
#    tag: 8

inputs:
- name: repo
- name: openjdk

#params:
#  pcf-username:
#  pcf-password:

run:
  path: sh
  args:
  - -exc
  - |
    echo "SOMETHING WORKS"

#caches:
#  - path: gradle