---
platform: linux

image_resource: openjdk

inputs:
- name: repo
- name: openjdk

#params:
#  pcf-username:
#  pcf-password:

run:
  path: sh
  args:
  - -exc
  - |
    echo "SOMETHING WORKS"

#caches:
#  - path: gradle