---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind

inputs:
- name: version
- name: repo
- name: postgres
- name: openjdk-node-cf

caches:
  - path: .gradle/

run:
  path: sh
  args:
  - -exc
  - |
    source /docker-lib.sh
    source repo/ci/tasks/common.sh

    start_docker

    docker load -i postgres/image
    docker load -i openjdk-node-cf/image

    docker images

    # Run the container with tests and its dependencies.
    docker-compose -f repo/ci/docker-compose.tests.yml up -d

    set -e

    export LUKE_DB_URL=jdbc:postgresql://localhost:5432/luke-test?user=lukeuser&password=lukepwd
    export  LUKE_DB_USERNAME=lukeuser
    export LUKE_DB_PASSWORD=lukepwd

    echo "about to run tests"
    echo "LUKE_DB_URL"
    echo $LUKE_DB_URL
    echo "LUKE_DB_USERNAME"
    echo $LUKE_DB_USERNAME
    echo "LUKE_DB_PASSWORD"
    echo $LUKE_DB_PASSWORD

    pushd repo
        ./gradlew clean test
        pushd client
            npm install
            npm test
        popd
    popd



    # Cleanup.
    # Not sure if this is required.
    # It's quite possible that Concourse is smart enough to clean up the Docker mess itself.
    docker-compose -f repo/ci/docker-compose.tests.yml down
    docker volume rm $(docker volume ls -q)