version: '3'

services:
  luke-db:
    image: postgres
    environment:
      POSTGRES_DB: luke-test
      POSTGRES_PASSWORD: lukepwd
      POSTGRES_USER: lukeuser
      PGDATA: /database

  unit-integration-tests:
    image: djdapz/openjdk-node-cf
    privileged: true
    links: [luke-db]
    depends_on: [luke-db]
    command: "./repo/ci/tasks/run-tests.sh"
    volumes:
      - ../:/repo
    environment:
      LUKE_DB_URL: jdbc:postgresql://luke-db:5432/luke-test
      LUKE_DB_PASSWORD: lukeuser
      LUKE_DB_USERNAME: lukepwd