---
resources:

- name: repo
  type: git
  source:
    uri: ((git-repo))
    private_key: ((github-private-key))

- name: openjdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8

- name: openjdk-npm-cf
  type: docker-image
  source:
    repository: djdapz/openjdk-node-cf
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:djdapz/lukeDapuzzo.git
    branch: version
    file: version
    private_key: ((github-private-key))

jobs:

- name: deploy-development
  public: true
  plan:
  - get: version
    trigger: true
  - get: repo
    trigger: true
  - get: openjdk-npm-cf
  - task: test
    privileged: true
    file: repo/ci/tasks/deploy-dev.yml
    image: openjdk-npm-cf
    params:
      PCF_USERNAME: ((PCF_USERNAME))
      PCF_PASSWORD: ((PCF_PASSWORD))
      PCF_SPACE: development
  - put: version
    params: {bump: patch}

- name: deploy-production
  public: true
  plan:
  - get: version
    passed: ["deploy-development"]
  - get: repo
    passed: ["deploy-development"]
  - get: openjdk-npm-cf
  - task: test
    privileged: true
    file: repo/ci/tasks/deploy-dev.yml
    image: openjdk-npm-cf
    params:
      PCF_USERNAME: ((PCF_USERNAME))
      PCF_PASSWORD: ((PCF_PASSWORD))
      PCF_SPACE: production


- name: build-openjdk-npm-cf
  plan:
  - get: repo
  - get: openjdk
  - task: build-openjdk-npm-cf
    file: repo/ci/openjdk/build-extended-openjdk.yml
  - put: openjdk-npm-cf
    params:
      build: workspace
