---
resources:

- name: repo
  type: git
  source:
    uri: ((git-repo))
    private_key: ((github-private-key))

- name: openjdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8

- name: postgres
  type: docker-image
  source:
    repository: postgres

- name: openjdk-node-cf
  type: docker-image
  source:
    repository: djdapz/openjdk-node-cf
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:djdapz/lukeDapuzzo.git
    branch: version
    file: version
    private_key: ((github-private-key))

jobs:

- name: run-tests
  public: true
  plan:
  - get: version
  - get: repo
    trigger: true
  - get: openjdk-node-cf
    params: {save: true}
  - get: postgres
    params: {save: true}
  - task: run-tests
    privileged: true
    file: repo/ci/tasks/run-tests.yml
  - put: version
    params: {bump: patch}

- name: run-tests-frontend
  public: true
  plan:
  - get: version
  - get: repo
    trigger: true
  - get: openjdk-node-cf
    params: {save: true}
  - get: postgres
    params: {save: true}
  - task: run-tests
    image: openjdk-node-cf
    privileged: true
    file: repo/ci/tasks/run-tests-frontend.yml

- name: bump-version
  plan:
  - get: repo
    trigger: true
    passed: ["run-tests-frontend", "run-tests"]
  - put: version
    params: {bump: patch}

- name: build-and-upload-frontend
  public: true
  plan:
  - get: version
    trigger: true
    passed: ["bump-version"]
  - get: repo
    trigger: true
    passed: ["bump-version"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: build-and-upload
    privileged: true
    file: repo/ci/tasks/build-and-upload-frontend.yml
    image: openjdk-node-cf
    params:
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))

- name: build-and-upload-backend
  public: true
  plan:
  - get: version
    trigger: true
    passed: ["bump-version"]
  - get: repo
    trigger: true
    passed: ["bump-version"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: build-and-upload
    privileged: true
    file: repo/ci/tasks/build-and-upload-backend.yml
    image: openjdk-node-cf
    params:
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))


- name: deploy-development-frontend
  public: true
  plan:
  - get: version
    trigger: true
    passed: ["build-and-upload-frontend"]
  - get: repo
    trigger: true
    passed: ["build-and-upload-frontend"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: deploy
    privileged: true
    file: repo/ci/tasks/deploy-cf-frontend.yml
    image: openjdk-node-cf
    params:
      PCF_USERNAME: ((PCF_USERNAME))
      PCF_PASSWORD: ((PCF_PASSWORD))
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
      PCF_SPACE: development
      LUKE_ENV: dev

- name: deploy-development-backend
  public: true
  plan:
  - get: version
    trigger: true
    passed: ["build-and-upload-backend"]
  - get: repo
    trigger: true
    passed: ["build-and-upload-backend"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: deploy
    privileged: true
    file: repo/ci/tasks/deploy-cf-backend.yml
    image: openjdk-node-cf
    params:
      PCF_USERNAME: ((PCF_USERNAME))
      PCF_PASSWORD: ((PCF_PASSWORD))
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
      PCF_SPACE: development
      LUKE_ENV: dev

- name: deploy-production-backend
  public: true
  plan:
  - get: version
    passed: ["deploy-development-backend"]
  - get: repo
    passed: ["deploy-development-backend"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: build-and-deploy
    privileged: true
    file: repo/ci/tasks/deploy-cf-backend.yml
    image: openjdk-node-cf
    params:
      PCF_USERNAME: ((PCF_USERNAME))
      PCF_PASSWORD: ((PCF_PASSWORD))
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
      PCF_SPACE: production
      LUKE_ENV: prod


- name: deploy-production-frontend
  public: true
  plan:
  - get: version
    passed: ["deploy-development-frontend"]
  - get: repo
    passed: ["deploy-development-frontend"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: build-and-deploy
    privileged: true
    file: repo/ci/tasks/deploy-cf-frontend.yml
    image: openjdk-node-cf
    params:
      PCF_USERNAME: ((PCF_USERNAME))
      PCF_PASSWORD: ((PCF_PASSWORD))
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
      PCF_SPACE: production
      LUKE_ENV: prod


- name: build-openjdk-node-cf
  plan:
  - get: repo
  - get: openjdk
  - task: build-openjdk-node-cf
    file: repo/ci/openjdk/build-extended-openjdk.yml
  - put: openjdk-node-cf
    params:
      build: workspace